version: '3.9'

services:
  sonicscribe-app:
    build: .
    container_name: sonicscribe-flaskapps
    ports:
      - "8080:5000"  # Maps external port 8080 to internal port 5000 (Gunicorn runs on 5000)
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
    environment:
      - FLASK_ENV=production  # Optional, for environment indication
