services:
  - type: web
    name: sonicscribe-app
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
    - key: OPENAI_API_KEY
      value: ${OPENAI_API_KEY}
    - key: LANGCHAIN_API_KEY
      value: ${LANGCHAIN_API_KEY}
    - key: LANGCHAIN_PROJECT
      value: Cyfuture
    - key: HF_TOKEN
      value: ${HF_TOKEN}
    autoDeploy: true
