services:
  - type: web
    name: sonicscribe-app
    env: docker
    repo: https://github.com/abhijeetmishra2104/sonicscribe-app1
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
    - key: OPENAI_API_KEY
      value: ${OPENAI_API_KEY}
    - key: LANGCHAIN_API_KEY
      value: ${LANGCHAIN_API_KEY}
    - key: LANGCHAIN_PROJECT
      value: Cyfuture
    - key: HF_TOKEN
      value: ${HF_TOKEN}
    autoDeploy: true
